{% set name = "jupyterlab-latex" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_latex/jupyterlab_latex-{{ version }}.tar.gz
  sha256: f44df285405b5b552b70d10f1f0573d61ca3a4d2ca50bd3097a63a27cdcde16e

build:
  noarch: python
  number: 0

requirements:
  build:
  host:
    - python >=3.6
  run:
    - python >=3.6
    - jupyterlab_latex

test:
  imports:
    - jupyterlab_latex
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: JupyterLab extension for live editing of LaTeX documents

  description: |
    An extension for JupyterLab which allows for live-editing of LaTeX 
    documents.
  doc_url: https://github.com/jupyterlab/jupyterlab-latex/blob/master/docs/advanced.md
  dev_url: https://github.com/jupyterlab/jupyterlab-latex

extra:
  recipe-maintainers:
    - jan-janssen
