{% set name = "jupyterlab-latex" %}
{% set version = "4.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyterlab/jupyterlab-latex/archive/v{{ version }}.tar.gz
  sha256: bec1f2bfd1086979285e9e369a9b0510e12f03a106e2bf1b570852ceea48a1f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - jupyter_packaging >=0.12,<1.dev0,<2
    - jupyterlab ==4.0.0
    - nodejs =18
    - pip
    - hatchling
    - hatch-nodejs-version
    - hatch-jupyter-builder
  run:
    - python >=3.8
    - jupyterlab >=4,<5
    - jupyter_server >=2,<3

test:
  imports:
    - jupyterlab_latex
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: JupyterLab extension for live editing of LaTeX documents

  description: |
    An extension for JupyterLab which allows for live-editing of LaTeX 
    documents.
  doc_url: https://github.com/jupyterlab/jupyterlab-latex/blob/master/docs/advanced.md
  dev_url: https://github.com/jupyterlab/jupyterlab-latex

extra:
  recipe-maintainers:
    - jan-janssen
